server:
  port: 8081

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:20000
              predicates:
                - Path=/api/auth/**
              filters:
                - PreserveHostHeader=true
            - id: product-service
              uri: http://localhost:20001
              predicates:
                - Path=/product/**
            - id: order-service
              uri: http://localhost:20002
              predicates:
                - Path=/order/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG