// user.service.ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { User } from './user.model';

@Injectable({
  providedIn: 'root'
})
export class UserService {
  private readonly apiUrl = 'http://localhost:20000/api/auth/';

  constructor(private http: HttpClient) {}

  getUsers(): Observable<User[]> {
    const token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJuaERJREFhNmZqbm1Ta3NEZEd1SldhdC1jUUxYYzlYN2FlVmdUODhiUEFnIn0.eyJleHAiOjE3NTUyNzMwMDksImlhdCI6MTc1NTI3MjcwOSwianRpIjoib25ydHJvOmEzZWJhYWI1LWEzOTktNDUxZC02NDc3LWQxMWE2YzJmZTE4MSIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvb3JkZXJmbG93IiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJhY2NvdW50Il0sInN1YiI6IjM2NmQwODQyLThkOWMtNGYwMC1hODlkLTY1ZmRmMmUyMmRiMiIsInR5cCI6IkJlYXJlciIsImF6cCI6Im9yZGVyZmxvdy1hcGkiLCJzaWQiOiI2ODMyYmQxZC0yZTEyLTRjNTItYjdmMi1lODAyZjdjNGFlNmIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtb3JkZXJmbG93Iiwib2ZmbGluZV9hY2Nlc3MiLCJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIiwidXNlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsibWFuYWdlLWNsaWVudHMiXX0sIm9yZGVyZmxvdy1hcGkiOnsicm9sZXMiOlsiYWRtaW4iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiS2FsZW16IEthbGVteiIsInByZWZlcnJlZF91c2VybmFtZSI6ImthbGVteiIsImdpdmVuX25hbWUiOiJLYWxlbXoiLCJmYW1pbHlfbmFtZSI6IkthbGVteiIsImVtYWlsIjoia2FsZW16QGdtYWlsLmNvbSJ9.gbjJ8gWJwi09fJvefOI7ZiAg0S6lpMn618GSZQzERCwe0NzgbXdVVsN2rn4X7BVVnqE0Qj74UBBmKmP1czEUGhTxxZo5DMTaUqCYIAbShZafI9tFaUi5yUJiB4mOTDO-4W07HFe2Uqy1dVL5p52b1ozM8Mu7y0_XzAAuWtX8THpc895G5cKcPWXNSGku8T5k-ppnFfELK3spGCWf1IkVgiLM9seruWHwdvoQ7Wk0Stbg6PtIA1BhGVEbXkxIc7XZJFFEbzliXxTiXJprt3kR3WE5IqNbkdCl5fKxxQBihbLbj0b9HrxTl-kHCDHr8p7yWgx_04vAfDT872JzvHIEtw";
    const headers = { 'Authorization': `Bearer ${token}` };
    return this.http.get<User[]>(this.apiUrl, { headers });
  }
}
